### ISSUE TITLE
Homepage content isn't centered

### ISSUE THREAD

**Issue by rafaelklaessen** [abseil/abseil.github.io#136]
The content of the homepage isn't centered, see screenshot below.
![screen shot 2018-01-10 at 21 31 08](https://user-images.githubusercontent.com/15846964/34794077-c582f422-f64d-11e7-9c20-d8bca726d549.png)
(Screenshot taken from Chrome running on MacOS.)

The container is aligned to the left (which is for the docs I suppose), which causes this behaviour.

**Comment by manshreck** [comment]
Fixed with webkit CSS fix.
