### ISSUE TITLE
Header collapses incorrectly

### ISSUE THREAD

**Issue by rafaelklaessen** [abseil/abseil.github.io#137]
When the header collapses, which occurs when you scroll down, it collapses in an incorrect fashion. (See screenshot below.)
![screen shot 2018-01-10 at 21 36 46](https://user-images.githubusercontent.com/15846964/34794457-0112a72a-f64f-11e7-9021-c3255f3bbce1.png)
(Screenshot taken from Chrome running on MacOS.)

**Comment by manshreck** [comment]
I believe I've partially addressed this in https://github.com/abseil/abseil.github.io/pull/189.
