### ISSUE TITLE
Interactive table for "Tips of the Week"

### ISSUE THREAD

**Issue by rongjiecomputer** [abseil/abseil.github.io#139]
I can understand why Abseil team prefers keeping the original numbering scheme and original publication date, but external readers who regularly return to check for new posts, it is not immediately clear whether there _is_ a new post after scanning the list in https://abseil.io/tips/.

Perhaps the `<ul>` list can be converted into an interactive `<table>` that can be sorted based on either original numbering scheme or external publication date?

**Comment by manshreck** [comment]
Good issue. 

FYI, we do have an RSS feed, which does list them in last-posted order:
http://feeds.feedburner.com/abseilio

This also lets you know when new tips are posted.

Still, you're right. This becomes more apparent with more tips. Perhaps we could simply have a chronological list on the main "tips" page (while the sidebar nav bar would continue to be ordered sequentially)?

**Comment by tituswinters** [comment]
In the short term - how about we just add a "new" tag.

**Comment by rongjiecomputer** [comment]
> In the short term - how about we just add a "new" tag.

Sounds good.

**Comment by manshreck** [comment]
I have a pull request out to address this:

https://github.com/abseil/abseil.github.io/pull/141

I'm not so keen on a "new" tag, as it loses contextual information (much like a "Garage Sale this Saturday" sign can't be trusted). Instead, I've sorted the tips on the main page in reverse order by publication date, and grouped them by their publication date. I think this will make it much easier to catch up, and keeps the dates of re-publication present so you can check what's changed.

(*I can also add a "new" graphic to the most recent set of tips, but it may be superfluous. Let me know.)

**Comment by manshreck** [comment]
Update: added to PR https://github.com/abseil/abseil.github.io/pull/144

**Comment by manshreck** [comment]
rongjiecomputer@, I've added the publishing dates in reverse order to the main tips page. Hopefully, this addresses your issue. (I think an interactive table would be both too complex and not user friendly.) Please re-open if you think this doesn't address the issue.
