### ISSUE TITLE
CMake/Bazel quickstart malformed link

### ISSUE THREAD

**Issue by Adrijaned** [abseil/abseil.github.io#282]
Near the top of CMake/Bazel quickstart guides are the links to the other, these return 404 due to linking to paths with the `.md` suffixes - these suffixes need to be removed.

**Comment by jonmeow** [comment]
NB: I think this was fixed at some point (https://abseil.io/docs/cpp/quickstart-cmake and https://abseil.io/docs/cpp/quickstart seem to have links that work)
