### ISSUE TITLE
Asking for permission to translate SWE books.

### ISSUE THREAD

**Issue by kok202** [abseil/abseil.github.io#382]
Hi, I'm a developer working on South Korea. First of all, I'm not good at in english. So please understand my awkward English skills.

And sorry for remaining question here, because I know this is not a right place for this sort of question. However, I heard the news the book was free from [here](https://github.com/abseil/abseil.github.io/blob/master/_posts/2021-04-22-swe-book.md), and  I couldn't find a suitable community to inquire, so I remain question here.

Anyway I want to asking for is it okay for translating SWE book to Korean. From the moment I found out that this book existed, that it was free, and that there was no translation, I have wanted to translate it. A few months after I started reading books while translating, and I just finished it. I worked that on my private repository and now I hope to turn it to the public github web page.

And before switching to public, I ask is it okay to switch. **I have no thoughts about commercial use.** And of course, if you want, I won't switch.

I've always been interested in Google's development culture. Personally, I was greatly influenced by reading the book, and I would like to contribute even a little to Korea's development culture. 

I look forward to your reply. Have a nice day.

**Comment by tituswinters** [comment]
Thank you for your interest and kind words.

Translations are handled by the publisher, so the appropriate channel would be to reach out to O'Reilly (they own the publishing rights).

That said, there is good news: last I heard from O'Reilly, there are translations in the works already for a number of languages, including Korean. I believe that it is being handled locally by Hanbit Media. 

I'm going to close this for now, but please feel free to reopen if you've got further questions.

**Comment by kok202** [comment]
@tituswinters 
Thank you for your answer.

I feel It's natural and interesting that the translation was already in progress. And at the same time, I'm sorry that I should've asked you in advance! It seems to be the characteristics of developers to try to hide what they do until it is completely completed as shown in the book. I repeated the same mistake. And I'm learning it again.

If the translation is in progress, it seems right not to switch to public. 

It is the most influenced book I have read recently. Thank you for writing a good book.
