### ISSUE TITLE
http://abseil.io/blog RSS or Atom?

### ISSUE THREAD

**Issue by bryceschober** [abseil/abseil.github.io#41]
Is it a blog without a feed? ;-)

**Comment by manshreck** [comment]
We will be deploying a feed soon, in time for our second post :) (for both tips and the Abseil blog).

**Comment by manshreck** [comment]
I've added feeds for both the blog and the tips. Closing this for now. Re-open if you find issues with the feeds!

http://feeds.feedburner.com/abseilio

**Comment by bryceschober** [comment]
Well, the article links I get from http://feeds.feedburner.com/abseilio seem to be using relative paths with http://feeds.feedburner.com as the root instead of https://abseil.io

**Comment by manshreck** [comment]
OK, I'll check this. It's likely a site url config, but I want to make sure it's localized to the feed component.

**Comment by manshreck** [comment]
This has been fixed for now. (Had to change site.baseurl to use site.url in the feed.xml file. I've tested this out and it seems to be working. (Make sure you give your reader enough time to resync the feed.
