### ISSUE TITLE
Unreadable footer area

### ISSUE THREAD

**Issue by yegle** [abseil/abseil.github.io#45]
The footer should be improved to have higher contrast.

This is a screenshot using Chrome under Linux:

![2017-09-26-120213_1583x326_scrot](https://user-images.githubusercontent.com/146133/30878831-911eba8e-a2b2-11e7-843c-55b976ea7b69.png)

**Comment by yegle** [comment]
Tom, while you are at it: it's better to improve the overall contrast since the font is too light (color-wise and style-wise). I see others ranting as well: https://news.ycombinator.com/item?id=15342041

**Comment by manshreck** [comment]
I believe this issue (links showing up in default blue color) has been fixed. Please re-open if you see it again (but make sure your cache is empty to reload the page.)

The text contrast is a separate issue and will be addressed separately.
