### ISSUE TITLE
Text on pages is really hard to read

### ISSUE THREAD

**Issue by evmar** [abseil/abseil.github.io#46]
Pages like http://abseil.io/about/philosophy use a gray font with a font-weight below "normal".  Depending on your screen technology / OS, this comes out as very thin lines that aren't even black.

Here are Google's docs on proper use of contrast, in case they are helpful:
https://developers.google.com/web/fundamentals/accessibility/accessible-styles#color_and_contrast

**Comment by evmar** [comment]
I'm not the only one to notice: https://news.ycombinator.com/item?id=15342041

**Comment by OlafvdSpek** [comment]
I was wondering about this too. Is it designed for hidpi displays? On a normal display it doesn't look right.

**Comment by manshreck** [comment]
We haven't had a lot of issues on this, and I haven't been able to duplicate this on any monitor/setting we have here. This is the default text rendering for a variety of Google open-source projects (proto, gRPC, TensorFlow, etc.) and I'm reluctant to diverge from it. As a result, I'm closing this for now.

If you can provide me with screenshots, specs for your monitors/etc., let me know.

**Comment by OlafvdSpek** [comment]
I've got a 27" 2560 x 1440 IPS monitor. No hidpi / text scaling / zoom.

![abseil](https://user-images.githubusercontent.com/2218936/33282953-9188c3e2-d3aa-11e7-9ff2-12f8282388b2.png)

**Comment by manshreck** [comment]
FYI, I am re-opening this for UX input. I am closing the PR, however, associated with this. I do think we should resolve this, but need to coordinate with the other open source teams using this template.

**Comment by manshreck** [comment]
FYI, I've updated the text contrast to be ~ 9.0 WCAG AAA guidelines in https://github.com/abseil/abseil.github.io/pull/188. 

The AAA guidelines state 7.0 should be the minimum for body text. (Current text is ~6.6). I'm adjusting upwards to account for the slightly smaller font size within abseil.io body text.

**Comment by OlafvdSpek** [comment]
Just wondering, why is font size smaller than normal?
