### ISSUE TITLE
Code samples in TOTW limited to 61 character width

### ISSUE THREAD

**Issue by camillol** [abseil/abseil.github.io#51]
See, for instance, https://abseil.io/tips/totw/1

The main text section is too narrow, and only fits 61 characters. You have to scroll horizontally to read the comments. The code blocks really should fit 80 characters, since all code in TOTW is going to be formatted for that width.

**Comment by manshreck** [comment]
Haven't quite fixed this issue, but am addressing it: removed margin from the left-most div (TOC), and changed code font within <pre> tags to be a bit smaller. Fits 80-columns now provided that the window is appropriately sized. Still need to narrow the left-most div, which is getting sized based on the sticky-nav above.

**Comment by manshreck** [comment]
I've tested this out on all pages and we can now fit 80 characters
