### ISSUE TITLE
Subscribe to TotW by email/RSS

### ISSUE THREAD

**Issue by achew22** [abseil/abseil.github.io#52]
Is it possible to create a RSS feed or an email subscription for when you release TotW? I'd love to learn more about C++ but I'm afraid I'll forget to come back and read the latest and greatest.

**Comment by manshreck** [comment]
We will be deploying this soon, for both tips and the blog.

**Comment by manshreck** [comment]
I've added feeds for both the blog and the tips. Closing this for now. Re-open if you find issues with the feeds!

http://feeds.feedburner.com/abseilio
